# Generated by Django 5.1.1 on 2024-11-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselected this instead of deleting.', verbose_name='Active status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified On')),
                ('content', models.TextField(verbose_name='content')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='dataset.dataset', verbose_name='dataset')),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselected this instead of deleting.', verbose_name='Active status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified On')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dataset.category', verbose_name='category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='text.text', verbose_name='text')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
